--LLAVE PARA EL CIFRADO
USE MASTER 
GO 
CREATE MASTER KEY ENCRYPTION BY PASSWORD = 'PASSWORD'
GO

-- CREACION DE CERTIFICADO
USE MASTER 
GO
CREATE CERTIFICATE CERTIFICADO_TDE WITH SUBJECT = 'TRANSPARENT DATA ENCRYPTION'
GO

---CREACION BD
create database ARE_Biblioteca_Legislativa
On
PRIMARY
       (NAME = AREPrimary,
		FILENAME = 'D:\ARE_Biblioteca\AREPrimary.mdf',
		SIZE = 500MB,
		MAXSIZE = 20000,
		FILEGROWTH = 20),
FILEGROUP AREFG
     ( NAME = AREData1,
       FILENAME = 'D:\ARE_Biblioteca\AREData1.nfd',
	   SIZE = 200MB,
	   MAXSIZE = 8000,
	   FILEGROWTH = 100),
      (NAME = AREData2,
	   FILENAME = 'D:\ARE_Biblioteca\AREData2.nfd', 	
	   SIZE = 400MB,
	   MAXSIZE = 12000,
	   FILEGROWTH = 300),
FILEGROUP AREHistoryFG
     ( NAME = AREHistory1,
       FILENAME = 'D:\ARE_Biblioteca\AREHistory1.nfd',
	   SIZE = 1000MB,
	   MAXSIZE = 50000,
	   FILEGROWTH = 50)
LOG ON
( NAME = Archlog1,
       FILENAME = 'D:\ARE_Biblioteca\ARELog.lfd',
	   SIZE = 300MB,
	   MAXSIZE = 8000,
	   FILEGROWTH = 100);   

--ON MASTER (DMK), CERTIFICADO Y (DEK)
USE ARE_Biblioteca_Legislativa
GO
CREATE DATABASE ENCRYPTION KEY WITH ALGORITHM = AES_128 ENCRYPTION BY SERVER CERTIFICATE CERTIFICADO_TDE;
GO

--HABILITAR TDE
USE MASTER;
ALTER DATABASE ARE_Biblioteca_Legislativa SET ENCRYPTION ON
GO

--VERIFICACION
SELECT name, is_encrypted FROM sys.databases where name = 'ARE_Biblioteca_Legislativa';
GO
SELECT DB_NAME(database_id) as DB_NAME, * FROM sys.dm_database_encryption_keys;
GO

--BACKUP CIFRADO

/* SE LE DA CLICK DERECHO SOBRE LA BASE EN EL MANAGMENT, SE SELECCIONA LA OPCION DE TASKS,
DE AHI SE ELIGE LA OPCION DE BACK UP, SE SELECCIONA (ARE_Biblioteca_Legislativa) Y SE LE DA OK

OJO CON LA RUTA DE SAVE DEL BACK UP */



--BACK UP DEL CERTIFICADO
BACKUP CERTIFICATE CERTIFICADO_TDE TO FILE ='RUTA USADA EN EL BACK UP ANTERIOR\cert.bak'
WITH PRIVATE KEY (FILE='RUTA USADA EN EL BACK UP ANTERIOR\certprivatekey.bak', ENCRYPTION BY PASSWORD = 'PASSWORD')
GO

--EL RESTORE SE HARIA:
RESTORE DATABASE ARE_Biblioteca_Legislativa
FROM DISK='RUTA USADA EN LOS BACK UP ANTERIORES\ARE_Biblioteca_Legislativa.bak'
GO

/* SE PUEDE HACER EL RESTORE CON CLICK DERECHO EN EL MANAGMENT SOBRE "DATABASES"... 
PERO ESE SERIA EL METODO NO VARON */